"""
Copyright (C) 2010 2011 Cisco Systems

This program is free software; you can redistribute it and/or         
modify it under the terms of the GNU General Public License         
as published by the Free Software Foundation; either version 2         
of the License, or (at your option) any later version.         
    
This program is distributed in the hope that it will be useful,         
but WITHOUT ANY WARRANTY; without even the implied warranty of         
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
GNU General Public License for more details.         
    
You should have received a copy of the GNU General Public License         
along with this program; if not, write to:         
The Free Software Foundation, Inc.         
59 Temple Place - Suite 330         
Boston, MA  02111-1307, USA.         
    
As a special exception, if other files instantiate classes, templates  
or use macros or inline functions from this project, or you compile         
this file and link it with other works to produce a work based         
on this file, this file does not by itself cause the resulting         
work to be covered by the GNU General Public License. However         
the source code for this file must still be made available in         
accordance with section (3) of the GNU General Public License.         
    
This exception does not invalidate any other reasons why a work         
based on this file might be covered by the GNU General Public         
License.
"""
# ============================================================================
# Created manually using smidump and RZ's custom version of ./libsmi2pysnmp
# Essentially::
#   $ smidump -f smiv2 CYBERSWITCHING-COMMON-MIB.txt \
#     >CYBERSWITCHING-COMMON-MIB.smiv2
#   $ smidump -f python CYBERSWITCHING-COMMON-MIB.smiv2 | \
#     ../libsmi2pysnmp >CYBERSWITCHING-COMMON-MIB.py
# --------------------------------------------------------------------------
# smidump: module `CYBERSWITCHING-COMMON-MIB.smiv2' contains errors, expect \
# flawed output
# ==========================================================================
# PySNMP SMI module. Autogenerated from smidump -f python CYBERSWITCHING-COMMON-MIB
# by libsmi2pysnmp-0.0.7-alpha-rz2 at Thu Dec 11 00:06:59 2008,
# Python version (2, 5, 2, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols('ASN1', 'Integer', 'ObjectIdentifier', 'OctetString')
( Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, Opaque, TimeTicks, Unsigned32, enterprises, ) = mibBuilder.importSymbols('SNMPv2-SMI', 'Bits', 'Counter32', 'Counter64', 'Gauge32', 'Integer32', 'IpAddress', 'MibIdentifier', 'MibScalar', 'MibTable', 'MibTableRow', 'MibTableColumn', 'Opaque', 'TimeTicks', 'Unsigned32', 'enterprises')
( DisplayString, ) = mibBuilder.importSymbols('SNMPv2-TC', 'DisplayString')

# Objects

cyberswitching = MibIdentifier((1, 3, 6, 1, 4, 1, 14300))
cyberswitching_products = MibIdentifier((1, 3, 6, 1, 4, 1, 14300, 1)).setLabel('cyberswitching-products')
tricomG2 = MibIdentifier((1, 3, 6, 1, 4, 1, 14300, 1, 2))
pm8 = MibIdentifier((1, 3, 6, 1, 4, 1, 14300, 1, 3))
systemInfo = MibIdentifier((1, 3, 6, 1, 4, 1, 14300, 2))
series = MibScalar((1, 3, 6, 1, 4, 1, 14300, 2, 1), DisplayString()).setMaxAccess('readonly').setDescription('The name of the product line of this product.')
model = MibScalar((1, 3, 6, 1, 4, 1, 14300, 2, 2), DisplayString()).setMaxAccess('readonly').setDescription('The specific model of the product.')
firmware_rev = MibScalar((1, 3, 6, 1, 4, 1, 14300, 2, 3), DisplayString()).setMaxAccess('readonly').setDescription('The firmware revision of the product.').setLabel('firmware-rev')
hardware_rev = MibScalar((1, 3, 6, 1, 4, 1, 14300, 2, 4), DisplayString()).setMaxAccess('readonly').setDescription('The hardware revision of the product.').setLabel('hardware-rev')
serialNumber = MibScalar((1, 3, 6, 1, 4, 1, 14300, 2, 5), DisplayString()).setMaxAccess('readonly').setDescription('The serial number of the product.')
manufactureDate = MibScalar((1, 3, 6, 1, 4, 1, 14300, 2, 6), DisplayString()).setMaxAccess('readonly').setDescription('The date of loading MAC address to unit.')

# Augmentions

# Exports

# Objects
mibBuilder.exportSymbols('CYBERSWITCHING-COMMON-MIB', cyberswitching=cyberswitching, cyberswitching_products=cyberswitching_products, tricomG2=tricomG2, pm8=pm8, systemInfo=systemInfo, series=series, model=model, firmware_rev=firmware_rev, hardware_rev=hardware_rev, serialNumber=serialNumber, manufactureDate=manufactureDate)

