"""
Copyright (C) 2010 2011 Cisco Systems

This program is free software; you can redistribute it and/or         
modify it under the terms of the GNU General Public License         
as published by the Free Software Foundation; either version 2         
of the License, or (at your option) any later version.         
    
This program is distributed in the hope that it will be useful,         
but WITHOUT ANY WARRANTY; without even the implied warranty of         
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
GNU General Public License for more details.         
    
You should have received a copy of the GNU General Public License         
along with this program; if not, write to:         
The Free Software Foundation, Inc.         
59 Temple Place - Suite 330         
Boston, MA  02111-1307, USA.         
    
As a special exception, if other files instantiate classes, templates  
or use macros or inline functions from this project, or you compile         
this file and link it with other works to produce a work based         
on this file, this file does not by itself cause the resulting         
work to be covered by the GNU General Public License. However         
the source code for this file must still be made available in         
accordance with section (3) of the GNU General Public License.         
    
This exception does not invalidate any other reasons why a work         
based on this file might be covered by the GNU General Public         
License.
"""
# ============================================================================
# Created via /home/mevans/source/pysnmp-experiments/Panduit-MIBs-1/PANDUIT.sh:
# 
# Use smidump and RZ's custom version of libsmi2pysnmp
# which was part of /home/mevans/source/pysnmp-experiments/ at the time of
# execution.
# 
# Essentially:
# 
# exec 5>PANDUIT-APPS-FWUPDATE-MIB.header 2>&5
# smidump --preload=./PANDUIT-REG.txt --preload=./PANDUIT-COMMON-MIB.txt -f python PANDUIT-APPS-FWUPDATE-MIB.txt | ../libsmi2pysnmp >PANDUIT-APPS-FWUPDATE-MIB.pysnmp
# cat PANDUIT-APPS-FWUPDATE-MIB.header | sed 's/^/# /g' >PANDUIT-APPS-FWUPDATE-MIB.py
# cat PANDUIT-APPS-FWUPDATE-MIB.pysnmp >>PANDUIT-APPS-FWUPDATE-MIB.py
# rm PANDUIT-APPS-FWUPDATE-MIB.pysnmp
# rm PANDUIT-APPS-FWUPDATE-MIB.header
# ----------------------------------------------------------------------------
# PANDUIT-APPS-FWUPDATE-MIB.txt:56: revision not in reverse chronological order
# WARNING: guessing DEFVAL type '0' for TimeTicks
# WARNING: guessing DEFVAL type '30000' for TimeTicks
# ==========================================================================
# PySNMP SMI module. Autogenerated from smidump -f python PANDUIT-APPS-FWUPDATE-MIB
# by libsmi2pysnmp-0.0.7-alpha-rz2 at Tue Oct 16 16:30:53 2007,
# Python version (2, 2, 3, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols('ASN1', 'Integer', 'ObjectIdentifier', 'OctetString')
( panduitIdentificationMAC, ) = mibBuilder.importSymbols('PANDUIT-COMMON-MIB', 'panduitIdentificationMAC')
( panduitApps, ) = mibBuilder.importSymbols('PANDUIT-REG', 'panduitApps')
( ModuleCompliance, NotificationGroup, ObjectGroup, ) = mibBuilder.importSymbols('SNMPv2-CONF', 'ModuleCompliance', 'NotificationGroup', 'ObjectGroup')
( Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, Opaque, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols('SNMPv2-SMI', 'Bits', 'Counter32', 'Counter64', 'Gauge32', 'Integer32', 'IpAddress', 'ModuleIdentity', 'MibIdentifier', 'NotificationType', 'ObjectIdentity', 'MibScalar', 'MibTable', 'MibTableRow', 'MibTableColumn', 'Opaque', 'TimeTicks', 'Unsigned32')
( DisplayString, TextualConvention, ) = mibBuilder.importSymbols('SNMPv2-TC', 'DisplayString', 'TextualConvention')

# Types

class PanFirmwareUpdateStatus(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(1,2,4,3,5,)
    namedValues = namedval.NamedValues(('inactive', 1), ('done', 2), ('verify', 3), ('download', 4), ('error', 5), )
    pass


# Objects

panduitAppsFWUpdate = ModuleIdentity((1, 3, 6, 1, 4, 1, 19536, 7, 8)).setRevisions(('2006-06-23 00:00','2006-05-12 00:00',))
panFWUpdateNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 8, 0))
panFWUpdateFileName = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 1), DisplayString()).setMaxAccess('readwrite').setDescription('The name of the firmware update file.')
panFWUpdateServerIP = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 2), IpAddress()).setMaxAccess('readwrite').setDescription('IP Address of the TFTP Server.')
panFWUpdateStatus = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 3), PanFirmwareUpdateStatus()).setMaxAccess('readwrite').setDescription('The current status of Firmware Update.')
panFWUpdateDelay = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 4), TimeTicks().clone(0)).setMaxAccess('readwrite').setDescription('Time to wait before starting the firmware update.\nValid Range 0..90000')
panFWUpdatErrCode = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 5), Integer32()).setMaxAccess('readonly').setDescription('An application-specific error code set when\na firmware update fails.')
panFWUpdateRetryinterval = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 6), TimeTicks().clone(30000)).setMaxAccess('readwrite').setDescription('Time to wait, when a firmware update\nfails, before trying again.\nValid range 0..90000 ')
panFWUpdateMaxRetry = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 7), Integer32().subtype(subtypeSpec=constraint.ValueRangeConstraint(1, 8)).clone(4)).setMaxAccess('readwrite').setDescription('Number of times to retry\nupdating the firmware.')
panFWUpdateLogFile = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 8), DisplayString()).setMaxAccess('readwrite').setDescription('A file written to the TFTP server if a \nfirmware update fails.')
panFWUpdateCmd = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 9), Integer().subtype(subtypeSpec=constraint.SingleValueConstraint(2,1,)).subtype(namedValues=namedval.NamedValues(('start', 1), ('cancel', 2), ))).setMaxAccess('readwrite').setDescription('Starts or stops the firmware update \nprocess.  start(1) is only allowed\nwhen panFWUpdateStatus is done(2)\nor error(5).')
panduitAppsFWUpdateConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 8, 10))
panduitAppsFWUpdateGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 8, 10, 1))
panduitAppsFWUpdateCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 8, 10, 2))
panFWUpdateErrLogFile = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 8, 11), DisplayString()).setMaxAccess('readonly').setDescription('A file written to the TFTP server if a \nfirmware update fails.')

# Augmentions

# Notifications

panFWUpdateStatusChange = NotificationType((1, 3, 6, 1, 4, 1, 19536, 7, 8, 0, 1)).setObjects(('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateStatus'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdatErrCode'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationMAC'), )

# Groups

panduitAppsFWUpdateGeneralGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 8, 10, 1, 1)).setObjects(('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateDelay'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateFileName'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdatErrCode'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateLogFile'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateStatus'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateServerIP'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateRetryinterval'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateMaxRetry'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateCmd'), )
panduitAppsFWUpdateGeneral2Group = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 8, 10, 1, 3)).setObjects(('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateDelay'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateFileName'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdatErrCode'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateErrLogFile'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateStatus'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateServerIP'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateRetryinterval'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateMaxRetry'), ('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateCmd'), )
panduitAppsFWUpdateNotificationGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 8, 10, 1, 2)).setObjects(('PANDUIT-APPS-FWUPDATE-MIB', 'panFWUpdateStatusChange'), )

# Exports

# Module identity
mibBuilder.exportSymbols('PANDUIT-APPS-FWUPDATE-MIB', PYSNMP_MODULE_ID=panduitAppsFWUpdate)

# Types
mibBuilder.exportSymbols('PANDUIT-APPS-FWUPDATE-MIB', PanFirmwareUpdateStatus=PanFirmwareUpdateStatus)

# Objects
mibBuilder.exportSymbols('PANDUIT-APPS-FWUPDATE-MIB', panduitAppsFWUpdate=panduitAppsFWUpdate, panFWUpdateNotifications=panFWUpdateNotifications, panFWUpdateFileName=panFWUpdateFileName, panFWUpdateServerIP=panFWUpdateServerIP, panFWUpdateStatus=panFWUpdateStatus, panFWUpdateDelay=panFWUpdateDelay, panFWUpdatErrCode=panFWUpdatErrCode, panFWUpdateRetryinterval=panFWUpdateRetryinterval, panFWUpdateMaxRetry=panFWUpdateMaxRetry, panFWUpdateLogFile=panFWUpdateLogFile, panFWUpdateCmd=panFWUpdateCmd, panduitAppsFWUpdateConformance=panduitAppsFWUpdateConformance, panduitAppsFWUpdateGroups=panduitAppsFWUpdateGroups, panduitAppsFWUpdateCompliances=panduitAppsFWUpdateCompliances, panFWUpdateErrLogFile=panFWUpdateErrLogFile)

# Notifications
mibBuilder.exportSymbols('PANDUIT-APPS-FWUPDATE-MIB', panFWUpdateStatusChange=panFWUpdateStatusChange)

# Groups
mibBuilder.exportSymbols('PANDUIT-APPS-FWUPDATE-MIB', panduitAppsFWUpdateGeneralGroup=panduitAppsFWUpdateGeneralGroup, panduitAppsFWUpdateGeneral2Group=panduitAppsFWUpdateGeneral2Group, panduitAppsFWUpdateNotificationGroup=panduitAppsFWUpdateNotificationGroup)
