"""
Copyright (C) 2010 2011 Cisco Systems

This program is free software; you can redistribute it and/or         
modify it under the terms of the GNU General Public License         
as published by the Free Software Foundation; either version 2         
of the License, or (at your option) any later version.         
    
This program is distributed in the hope that it will be useful,         
but WITHOUT ANY WARRANTY; without even the implied warranty of         
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
GNU General Public License for more details.         
    
You should have received a copy of the GNU General Public License         
along with this program; if not, write to:         
The Free Software Foundation, Inc.         
59 Temple Place - Suite 330         
Boston, MA  02111-1307, USA.         
    
As a special exception, if other files instantiate classes, templates  
or use macros or inline functions from this project, or you compile         
this file and link it with other works to produce a work based         
on this file, this file does not by itself cause the resulting         
work to be covered by the GNU General Public License. However         
the source code for this file must still be made available in         
accordance with section (3) of the GNU General Public License.         
    
This exception does not invalidate any other reasons why a work         
based on this file might be covered by the GNU General Public         
License.
"""
# ============================================================================
# Created via /home/mevans/source/pysnmp-experiments/Panduit-MIBs-1/PANDUIT.sh:
# 
# Use smidump and RZ's custom version of libsmi2pysnmp
# which was part of /home/mevans/source/pysnmp-experiments/ at the time of
# execution.
# 
# Essentially:
# 
# exec 5>PANDUIT-TC.header 2>&5
# smidump  -f python PANDUIT-TC.txt | ../libsmi2pysnmp >PANDUIT-TC.pysnmp
# cat PANDUIT-TC.header | sed 's/^/# /g' >PANDUIT-TC.py
# cat PANDUIT-TC.pysnmp >>PANDUIT-TC.py
# rm PANDUIT-TC.pysnmp
# rm PANDUIT-TC.header
# ----------------------------------------------------------------------------
# PANDUIT-TC.txt:91: identifier `dur_0ms' must not contain an underscore
# PANDUIT-TC.txt:92: identifier `dur_500ms' must not contain an underscore
# PANDUIT-TC.txt:93: identifier `dur_1000ms' must not contain an underscore
# PANDUIT-TC.txt:94: identifier `dur_1500ms' must not contain an underscore
# PANDUIT-TC.txt:95: identifier `dur_2000ms' must not contain an underscore
# PANDUIT-TC.txt:96: identifier `dur_2500ms' must not contain an underscore
# PANDUIT-TC.txt:97: identifier `dur_3000ms' must not contain an underscore
# PANDUIT-TC.txt:98: identifier `dur_3500ms' must not contain an underscore
# PANDUIT-TC.txt:99: identifier `dur_4000ms' must not contain an underscore
# PANDUIT-TC.txt:100: identifier `dur_4500ms' must not contain an underscore
# PANDUIT-TC.txt:101: identifier `dur_5000ms' must not contain an underscore
# PANDUIT-TC.txt:138: identifier `legacy_and_802_3af' must not contain an underscore
# PANDUIT-TC.txt:139: identifier `only802_3af' must not contain an underscore
# PANDUIT-TC.txt:156: identifier `ac_dc' must not contain an underscore
# PANDUIT-TC.txt:165: identifier `delay_10ms' must not contain an underscore
# PANDUIT-TC.txt:166: identifier `delay_20ms' must not contain an underscore
# PANDUIT-TC.txt:167: identifier `delay_30ms' must not contain an underscore
# PANDUIT-TC.txt:168: identifier `delay_40ms' must not contain an underscore
# PANDUIT-TC.txt:169: identifier `delay_50ms' must not contain an underscore
# PANDUIT-TC.txt:204: missing MODULE-IDENTITY clause in SMIv2 MIB
# smidump: module `PANDUIT-TC.txt' contains errors, expect flawed output
# ==========================================================================
# PySNMP SMI module. Autogenerated from smidump -f python PANDUIT-TC
# by libsmi2pysnmp-0.0.7-alpha-rz2 at Tue Oct 16 16:30:54 2007,
# Python version (2, 2, 3, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols('ASN1', 'Integer', 'ObjectIdentifier', 'OctetString')
( Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, MibIdentifier, Opaque, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols('SNMPv2-SMI', 'Bits', 'Counter32', 'Counter64', 'Gauge32', 'Integer32', 'IpAddress', 'MibIdentifier', 'Opaque', 'TimeTicks', 'Unsigned32')
( TextualConvention, ) = mibBuilder.importSymbols('SNMPv2-TC', 'TextualConvention')

# Types

class PanduitAccessLevel(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(2,1,)
    namedValues = namedval.NamedValues(('readOnly', 1), ('readWrite', 2), )
    pass

class PanduitBlinkState(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(1,2,)
    namedValues = namedval.NamedValues(('blink', 1), ('steady', 2), )
    pass

class PanduitDuration(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(2,9,1,11,8,4,3,10,5,6,7,)
    namedValues = namedval.NamedValues(('dur_0ms', 1), ('dur_4500ms', 10), ('dur_5000ms', 11), ('dur_500ms', 2), ('dur_1000ms', 3), ('dur_1500ms', 4), ('dur_2000ms', 5), ('dur_2500ms', 6), ('dur_3000ms', 7), ('dur_3500ms', 8), ('dur_4000ms', 9), )
    pass

class PanduitEnable(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(2,1,)
    namedValues = namedval.NamedValues(('enabled', 1), ('disabled', 2), )
    pass

class PanduitLedColor(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(4,2,1,3,)
    namedValues = namedval.NamedValues(('off', 1), ('green', 2), ('red', 3), ('amber', 4), )
    pass

class PanduitLongDisplayString(TextualConvention, OctetString):
    displayHint = '1024a'
    subtypeSpec = OctetString.subtypeSpec+constraint.ValueSizeConstraint(0,1024)
    pass

class PanduitOverride(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(2,1,)
    namedValues = namedval.NamedValues(('normal', 1), ('override', 2), )
    pass

class PanduitPoEDetectType(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(2,3,1,)
    namedValues = namedval.NamedValues(('legacy_and_802_3af', 1), ('only802_3af', 2), ('onlylegacy', 3), )
    pass

class PanduitPoEForcePowerType(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(3,1,2,)
    namedValues = namedval.NamedValues(('none', 1), ('forcedDeviceCheck', 2), ('forced', 3), )
    pass

class PanduitPoELegacyDelay(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(4,2,1,5,3,)
    namedValues = namedval.NamedValues(('delay_10ms', 1), ('delay_20ms', 2), ('delay_30ms', 3), ('delay_40ms', 4), ('delay_50ms', 5), )
    pass

class PanduitPoEMPSType(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(2,1,3,)
    namedValues = namedval.NamedValues(('dc', 1), ('ac', 2), ('ac_dc', 3), )
    pass

class PanduitPoEVoltageType(TextualConvention, Integer32):
    displayHint = 'd-2'
    pass


# Exports

# Types
mibBuilder.exportSymbols('PANDUIT-TC', PanduitAccessLevel=PanduitAccessLevel, PanduitBlinkState=PanduitBlinkState, PanduitDuration=PanduitDuration, PanduitEnable=PanduitEnable, PanduitLedColor=PanduitLedColor, PanduitLongDisplayString=PanduitLongDisplayString, PanduitOverride=PanduitOverride, PanduitPoEDetectType=PanduitPoEDetectType, PanduitPoEForcePowerType=PanduitPoEForcePowerType, PanduitPoELegacyDelay=PanduitPoELegacyDelay, PanduitPoEMPSType=PanduitPoEMPSType, PanduitPoEVoltageType=PanduitPoEVoltageType)

