"""
Copyright (C) 2010 2011 Cisco Systems

This program is free software; you can redistribute it and/or         
modify it under the terms of the GNU General Public License         
as published by the Free Software Foundation; either version 2         
of the License, or (at your option) any later version.         
    
This program is distributed in the hope that it will be useful,         
but WITHOUT ANY WARRANTY; without even the implied warranty of         
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
GNU General Public License for more details.         
    
You should have received a copy of the GNU General Public License         
along with this program; if not, write to:         
The Free Software Foundation, Inc.         
59 Temple Place - Suite 330         
Boston, MA  02111-1307, USA.         
    
As a special exception, if other files instantiate classes, templates  
or use macros or inline functions from this project, or you compile         
this file and link it with other works to produce a work based         
on this file, this file does not by itself cause the resulting         
work to be covered by the GNU General Public License. However         
the source code for this file must still be made available in         
accordance with section (3) of the GNU General Public License.         
    
This exception does not invalidate any other reasons why a work         
based on this file might be covered by the GNU General Public         
License.
"""
# ============================================================================
# Created via /home/mevans/source/pysnmp-experiments/Panduit-MIBs-1/PANDUIT.sh:
# 
# Use smidump and RZ's custom version of libsmi2pysnmp
# which was part of /home/mevans/source/pysnmp-experiments/ at the time of
# execution.
# 
# Essentially:
# 
# exec 5>PANDUIT-APPS-LED-MIB.header 2>&5
# smidump --preload=./PANDUIT-REG.txt --preload=./PANDUIT-TC.txt -f python PANDUIT-APPS-LED-MIB.txt | ../libsmi2pysnmp >PANDUIT-APPS-LED-MIB.pysnmp
# cat PANDUIT-APPS-LED-MIB.header | sed 's/^/# /g' >PANDUIT-APPS-LED-MIB.py
# cat PANDUIT-APPS-LED-MIB.pysnmp >>PANDUIT-APPS-LED-MIB.py
# rm PANDUIT-APPS-LED-MIB.pysnmp
# rm PANDUIT-APPS-LED-MIB.header
# ----------------------------------------------------------------------------
# PANDUIT-APPS-LED-MIB.txt:51: revision not in reverse chronological order
# ==========================================================================
# PySNMP SMI module. Autogenerated from smidump -f python PANDUIT-APPS-LED-MIB
# by libsmi2pysnmp-0.0.7-alpha-rz2 at Tue Oct 16 16:30:53 2007,
# Python version (2, 2, 3, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols('ASN1', 'Integer', 'ObjectIdentifier', 'OctetString')
( panduitApps, ) = mibBuilder.importSymbols('PANDUIT-REG', 'panduitApps')
( PanduitBlinkState, PanduitDuration, PanduitLedColor, PanduitOverride, ) = mibBuilder.importSymbols('PANDUIT-TC', 'PanduitBlinkState', 'PanduitDuration', 'PanduitLedColor', 'PanduitOverride')
( ModuleCompliance, ObjectGroup, ) = mibBuilder.importSymbols('SNMPv2-CONF', 'ModuleCompliance', 'ObjectGroup')
( Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, Opaque, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols('SNMPv2-SMI', 'Bits', 'Counter32', 'Counter64', 'Gauge32', 'Integer32', 'IpAddress', 'ModuleIdentity', 'MibIdentifier', 'ObjectIdentity', 'MibScalar', 'MibTable', 'MibTableRow', 'MibTableColumn', 'Opaque', 'TimeTicks', 'Unsigned32')

# Objects

panduitAppsLED = ModuleIdentity((1, 3, 6, 1, 4, 1, 19536, 7, 4)).setRevisions(('2006-05-15 00:00','2005-04-29 00:00',))
panduitLEDPortLedTable = MibTable((1, 3, 6, 1, 4, 1, 19536, 7, 4, 1)).setDescription('Led information by Port.')
panduitLEDPortLedEntry = MibTableRow((1, 3, 6, 1, 4, 1, 19536, 7, 4, 1, 1)).setIndexNames((0, 'PANDUIT-APPS-LED-MIB', 'panduitLEDPortLedIndex')).setDescription('Port LED Table Row definition')
panduitLEDPortLedIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 4, 1, 1, 1), Unsigned32().subtype(subtypeSpec=constraint.ValueRangeConstraint(1, 2147483647L))).setMaxAccess('noaccess').setDescription('Table index.')
panduitLEDPortLedColor = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 4, 1, 1, 2), PanduitLedColor()).setMaxAccess('readwrite').setDescription('LED Color.')
panduitLEDPortLedRate = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 4, 1, 1, 3), PanduitBlinkState()).setMaxAccess('readwrite').setDescription('LED Blink status.  Can be set to blink or steady.')
panduitLEDPortLedOverride = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 4, 1, 1, 4), PanduitOverride()).setMaxAccess('readwrite').setDescription('Override normal functionality.  Normal functionality is \nto flash green.  To override, set this value to override(2)\nand set panduitLEDPortLedColor, panduitLEDPortLedRate,\nand panduitLEDPortLEDPeriod to achieve the desired result.')
panduitLEDPortLedPeriod = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 4, 2), PanduitDuration()).setMaxAccess('readwrite').setDescription('Override normal functionality.  Normal functionality is \nto flash green.  To override, set this value to override(2)\nand set panduitLEDPortLedColor, panduitLEDPortLedRate,\nand panduitLEDPortLEDPeriod to achieve the desired result.')
panduitLEDSystemLedTable = MibTable((1, 3, 6, 1, 4, 1, 19536, 7, 4, 3)).setDescription('Led information by Port.')
panduitLEDSystemLedEntry = MibTableRow((1, 3, 6, 1, 4, 1, 19536, 7, 4, 3, 1)).setIndexNames((0, 'PANDUIT-APPS-LED-MIB', 'panduitLEDSystemLedIndex')).setDescription('A row in the Trap Receiver Table.')
panduitLEDSystemLedIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 4, 3, 1, 1), Unsigned32().subtype(subtypeSpec=constraint.ValueRangeConstraint(1, 2147483647L))).setMaxAccess('noaccess').setDescription('Table Index.')
panduitLEDSystemLedColor = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 4, 3, 1, 2), PanduitLedColor()).setMaxAccess('readwrite').setDescription('LED Color.')
panduitLEDSystemLedRate = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 4, 3, 1, 3), PanduitBlinkState()).setMaxAccess('readwrite').setDescription('LED Blink status.  Can be set to blink or steady.')
panduitLEDSystemLedOverride = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 4, 3, 1, 4), PanduitOverride()).setMaxAccess('readwrite').setDescription('Override normal functionality.  Normal functionality is \nto flash green.  To override, set this value to override(2)\nand set panduitLEDSystemLedColor, panduitLEDSystemLedRate,\nand panduitLEDSystemLedPeriod to achieve the desired result.')
panduitLEDSystemLedPeriod = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 4, 4), PanduitDuration()).setMaxAccess('readwrite').setDescription('Override normal functionality.  Normal functionality is \nto flash green.  To override, set this value to override(2)\nand set panduitLEDSystemLedColor, panduitLEDSystemLedRate,\nand panduitLEDSystemLedPeriod to achieve the desired result.')
panduitAppsLEDConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 4, 5))
panduitAppsLEDGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 4, 5, 1))
panduitAppsLEDCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 4, 5, 2))

# Augmentions

# Groups

panduitAppsLEDPortLEDGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 4, 5, 1, 1)).setObjects(('PANDUIT-APPS-LED-MIB', 'panduitLEDPortLedRate'), ('PANDUIT-APPS-LED-MIB', 'panduitLEDPortLedPeriod'), ('PANDUIT-APPS-LED-MIB', 'panduitLEDPortLedOverride'), ('PANDUIT-APPS-LED-MIB', 'panduitLEDPortLedColor'), )
panduitAppsLEDSystemLEDGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 4, 5, 1, 2)).setObjects(('PANDUIT-APPS-LED-MIB', 'panduitLEDSystemLedRate'), ('PANDUIT-APPS-LED-MIB', 'panduitLEDSystemLedPeriod'), ('PANDUIT-APPS-LED-MIB', 'panduitLEDSystemLedOverride'), ('PANDUIT-APPS-LED-MIB', 'panduitLEDSystemLedColor'), )

# Exports

# Module identity
mibBuilder.exportSymbols('PANDUIT-APPS-LED-MIB', PYSNMP_MODULE_ID=panduitAppsLED)

# Objects
mibBuilder.exportSymbols('PANDUIT-APPS-LED-MIB', panduitAppsLED=panduitAppsLED, panduitLEDPortLedTable=panduitLEDPortLedTable, panduitLEDPortLedEntry=panduitLEDPortLedEntry, panduitLEDPortLedIndex=panduitLEDPortLedIndex, panduitLEDPortLedColor=panduitLEDPortLedColor, panduitLEDPortLedRate=panduitLEDPortLedRate, panduitLEDPortLedOverride=panduitLEDPortLedOverride, panduitLEDPortLedPeriod=panduitLEDPortLedPeriod, panduitLEDSystemLedTable=panduitLEDSystemLedTable, panduitLEDSystemLedEntry=panduitLEDSystemLedEntry, panduitLEDSystemLedIndex=panduitLEDSystemLedIndex, panduitLEDSystemLedColor=panduitLEDSystemLedColor, panduitLEDSystemLedRate=panduitLEDSystemLedRate, panduitLEDSystemLedOverride=panduitLEDSystemLedOverride, panduitLEDSystemLedPeriod=panduitLEDSystemLedPeriod, panduitAppsLEDConformance=panduitAppsLEDConformance, panduitAppsLEDGroups=panduitAppsLEDGroups, panduitAppsLEDCompliances=panduitAppsLEDCompliances)

# Groups
mibBuilder.exportSymbols('PANDUIT-APPS-LED-MIB', panduitAppsLEDPortLEDGroup=panduitAppsLEDPortLEDGroup, panduitAppsLEDSystemLEDGroup=panduitAppsLEDSystemLEDGroup)
