"""
Copyright (C) 2010 2011 Cisco Systems

This program is free software; you can redistribute it and/or         
modify it under the terms of the GNU General Public License         
as published by the Free Software Foundation; either version 2         
of the License, or (at your option) any later version.         
    
This program is distributed in the hope that it will be useful,         
but WITHOUT ANY WARRANTY; without even the implied warranty of         
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
GNU General Public License for more details.         
    
You should have received a copy of the GNU General Public License         
along with this program; if not, write to:         
The Free Software Foundation, Inc.         
59 Temple Place - Suite 330         
Boston, MA  02111-1307, USA.         
    
As a special exception, if other files instantiate classes, templates  
or use macros or inline functions from this project, or you compile         
this file and link it with other works to produce a work based         
on this file, this file does not by itself cause the resulting         
work to be covered by the GNU General Public License. However         
the source code for this file must still be made available in         
accordance with section (3) of the GNU General Public License.         
    
This exception does not invalidate any other reasons why a work         
based on this file might be covered by the GNU General Public         
License.
"""
# ============================================================================
# Created via /home/mevans/source/pysnmp-experiments/Panduit-MIBs-1/PANDUIT.sh:
# 
# Use smidump and RZ's custom version of libsmi2pysnmp
# which was part of /home/mevans/source/pysnmp-experiments/ at the time of
# execution.
# 
#   NOTE:  This file renamed PANDUIT-APPS-PoE-MIB.txt to match the name of the
#          MIB.
# 
# Essentially:
# 
# exec 5>PANDUIT-APPS-PoE-MIB.header 2>&5
# smidump --preload=./PANDUIT-REG.txt --preload=./PANDUIT-TC.txt --preload=./PANDUIT-COMMON-MIB.txt --preload=./PANDUIT-PRODUCTS-PANEL-COMMON-MIB.txt -f python PANDUIT-APPS-PoE-MIB.txt | ../libsmi2pysnmp >PANDUIT-APPS-PoE-MIB.pysnmp
# cat PANDUIT-APPS-PoE-MIB.header | sed 's/^/# /g' >PANDUIT-APPS-PoE-MIB.py
# cat PANDUIT-APPS-PoE-MIB.pysnmp >>PANDUIT-APPS-PoE-MIB.py
# rm PANDUIT-APPS-PoE-MIB.pysnmp
# rm PANDUIT-APPS-PoE-MIB.header
# ----------------------------------------------------------------------------
# PANDUIT-APPS-PoE-MIB.txt:75: revision not in reverse chronological order
# PANDUIT-APPS-PoE-MIB.txt:80: revision not in reverse chronological order
# ==========================================================================
# PySNMP SMI module. Autogenerated from smidump -f python PANDUIT-APPS-PoE-MIB
# by libsmi2pysnmp-0.0.7-alpha-rz2 at Tue Oct 16 16:30:53 2007,
# Python version (2, 2, 3, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols('ASN1', 'Integer', 'ObjectIdentifier', 'OctetString')
( panduitCommonNotifyPortNumber, panduitIdentificationLocation, panduitIdentificationMAC, ) = mibBuilder.importSymbols('PANDUIT-COMMON-MIB', 'panduitCommonNotifyPortNumber', 'panduitIdentificationLocation', 'panduitIdentificationMAC')
( panduitProdPanelCommonRackId, panduitProdPanelCommonRackPositionId, ) = mibBuilder.importSymbols('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackId', 'panduitProdPanelCommonRackPositionId')
( panduitApps, ) = mibBuilder.importSymbols('PANDUIT-REG', 'panduitApps')
( PanduitEnable, PanduitPoEDetectType, PanduitPoEForcePowerType, PanduitPoELegacyDelay, PanduitPoEMPSType, ) = mibBuilder.importSymbols('PANDUIT-TC', 'PanduitEnable', 'PanduitPoEDetectType', 'PanduitPoEForcePowerType', 'PanduitPoELegacyDelay', 'PanduitPoEMPSType')
( pethPsePortPowerClassifications, pethPsePortType, ) = mibBuilder.importSymbols('POWER-ETHERNET-MIB', 'pethPsePortPowerClassifications', 'pethPsePortType')
( ModuleCompliance, NotificationGroup, ObjectGroup, ) = mibBuilder.importSymbols('SNMPv2-CONF', 'ModuleCompliance', 'NotificationGroup', 'ObjectGroup')
( sysName, ) = mibBuilder.importSymbols('SNMPv2-MIB', 'sysName')
( Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, Opaque, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols('SNMPv2-SMI', 'Bits', 'Counter32', 'Counter64', 'Gauge32', 'Integer32', 'IpAddress', 'ModuleIdentity', 'MibIdentifier', 'NotificationType', 'ObjectIdentity', 'MibScalar', 'MibTable', 'MibTableRow', 'MibTableColumn', 'Opaque', 'TimeTicks', 'Unsigned32')
( TextualConvention, ) = mibBuilder.importSymbols('SNMPv2-TC', 'TextualConvention')

# Types

class PanduitPoEPlusOperMode(Integer):
    subtypeSpec = Integer.subtypeSpec+constraint.SingleValueConstraint(1,3,2,)
    namedValues = namedval.NamedValues(('off', 1), ('manual', 2), ('auto', 3), )
    pass


# Objects

panduitAppsPoE = ModuleIdentity((1, 3, 6, 1, 4, 1, 19536, 7, 1)).setRevisions(('2006-05-09 00:00','2005-11-21 00:00','2005-04-28 00:00',))
panduitAppsPoENotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 1, 0))
panduitPoEPoETable = MibTable((1, 3, 6, 1, 4, 1, 19536, 7, 1, 1)).setDescription('PoE information by Port.')
panduitPoEPoEEntry = MibTableRow((1, 3, 6, 1, 4, 1, 19536, 7, 1, 1, 1)).setIndexNames((0, 'PANDUIT-APPS-PoE-MIB', 'panduitPoEPoEIndex')).setDescription('A row in the PoE Table.')
panduitPoEPoEIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 1, 1, 1, 1), Unsigned32().subtype(subtypeSpec=constraint.ValueRangeConstraint(1, 2147483647L))).setMaxAccess('noaccess').setDescription('Table Index.')
panduitPoEPoEForcePwr = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 1, 1, 1, 2), PanduitPoEForcePowerType()).setMaxAccess('readwrite').setDescription('Allows power to be forced for PDs that can not be \ndetected by PSE.  Not all PDs may be supported.')
panduitPoEPoEDetectControl = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 1, 1, 1, 3), PanduitPoEDetectType()).setMaxAccess('readwrite').setDescription('Determines what PD types will be detected.')
panduitPoEPoEMPSType = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 1, 1, 1, 4), PanduitPoEMPSType()).setMaxAccess('readwrite').setDescription('The Maintain Power Signature component(s) monitored by the PSE.')
panduitPoELegacyDelay = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 1, 2), PanduitPoELegacyDelay()).setMaxAccess('readwrite').setDescription('Length of time to detect a legacy PD.')
panduitPoEPlus = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3))
panduitPoEPlusScalarObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 1))
panduitPoEPlusHiPwrEnable = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 1, 1), PanduitPoEPlusOperMode()).setMaxAccess('readwrite').setDescription('Enables PoE plus for the managed object\nand controls whether max power is \ndetermined automatically.')
panduitPoePlusPDPowerMonEnable = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 1, 3), PanduitEnable()).setMaxAccess('readwrite').setDescription('Enables PD Class Power Monitoring.\nPDs drawing more power than\ndetermined by classification\nare shutdown.')
panduitPoePlusBackoffEnable = MibScalar((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 1, 4), PanduitEnable()).setMaxAccess('readwrite').setDescription('Enables cadence timing per the \nIEE 802.3af specification.')
panduitPoEPlusTabularObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 2))
panduitPoePlusPortPowerTable = MibTable((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 2, 1)).setDescription('PoE Plus Power information by Port.')
panduitPoePlusPortPowerEntry = MibTableRow((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 2, 1, 1)).setIndexNames((0, 'PANDUIT-APPS-PoE-MIB', 'panduitPoePlusPortPwrIndex')).setDescription('A row in the Trap Receiver Table.')
panduitPoePlusPortPwrIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 2, 1, 1, 1), Unsigned32().subtype(subtypeSpec=constraint.ValueRangeConstraint(1, 2147483647L))).setMaxAccess('noaccess').setDescription('Table Index.')
panduitPoePlusPortPwrMaxPower = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 2, 1, 1, 2), Integer32().subtype(subtypeSpec=constraint.ValueRangeConstraint(26, 26))).setMaxAccess('readwrite').setDescription('Table Index.')
panduitPoePlusPortPwrActPower = MibTableColumn((1, 3, 6, 1, 4, 1, 19536, 7, 1, 3, 2, 1, 1, 3), Unsigned32()).setMaxAccess('readonly').setDescription('Table Index.')
panduitAppsPoEConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 1, 4))
panduitAppsPoEGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 1, 4, 1))
panduitAppsPoECompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 19536, 7, 1, 4, 2))

# Augmentions

# Notifications

panduitPoEPortPowerStatusOff = NotificationType((1, 3, 6, 1, 4, 1, 19536, 7, 1, 0, 2)).setObjects(('PANDUIT-COMMON-MIB', 'panduitCommonNotifyPortNumber'), ('SNMPv2-MIB', 'sysName'), ('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackId'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationMAC'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationLocation'), ('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackPositionId'), ('POWER-ETHERNET-MIB', 'pethPsePortPowerClassifications'), )
panduitPoEPortPDDetectionFault = NotificationType((1, 3, 6, 1, 4, 1, 19536, 7, 1, 0, 4)).setObjects(('PANDUIT-COMMON-MIB', 'panduitCommonNotifyPortNumber'), ('SNMPv2-MIB', 'sysName'), ('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackId'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationMAC'), ('POWER-ETHERNET-MIB', 'pethPsePortType'), ('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackPositionId'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationLocation'), )
panduitPoEPortPowerStatusOn = NotificationType((1, 3, 6, 1, 4, 1, 19536, 7, 1, 0, 1)).setObjects(('PANDUIT-COMMON-MIB', 'panduitCommonNotifyPortNumber'), ('SNMPv2-MIB', 'sysName'), ('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackId'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationMAC'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationLocation'), ('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackPositionId'), ('POWER-ETHERNET-MIB', 'pethPsePortPowerClassifications'), )
panduitPoEPortPowerStatusFault = NotificationType((1, 3, 6, 1, 4, 1, 19536, 7, 1, 0, 3)).setObjects(('PANDUIT-COMMON-MIB', 'panduitCommonNotifyPortNumber'), ('SNMPv2-MIB', 'sysName'), ('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackId'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationMAC'), ('PANDUIT-COMMON-MIB', 'panduitIdentificationLocation'), ('PANDUIT-PRODUCTS-PANEL-COMMON-MIB', 'panduitProdPanelCommonRackPositionId'), ('POWER-ETHERNET-MIB', 'pethPsePortPowerClassifications'), )

# Groups

panduitAppsPoEGeneralGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 1, 4, 1, 1)).setObjects(('PANDUIT-APPS-PoE-MIB', 'panduitPoEPoEMPSType'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoEPoEForcePwr'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoEPoEDetectControl'), )
panduitAppsPoEDeprecatedGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 1, 4, 1, 3)).setObjects(('PANDUIT-APPS-PoE-MIB', 'panduitPoELegacyDelay'), )
panduitAppsPoENotificationGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 1, 4, 1, 2)).setObjects(('PANDUIT-APPS-PoE-MIB', 'panduitPoEPortPowerStatusOff'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoEPortPDDetectionFault'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoEPortPowerStatusOn'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoEPortPowerStatusFault'), )
panduitAppsPoEPoEPlusGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 19536, 7, 1, 4, 1, 4)).setObjects(('PANDUIT-APPS-PoE-MIB', 'panduitPoePlusPDPowerMonEnable'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoePlusPortPwrMaxPower'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoePlusPortPwrActPower'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoePlusBackoffEnable'), ('PANDUIT-APPS-PoE-MIB', 'panduitPoEPlusHiPwrEnable'), )

# Exports

# Module identity
mibBuilder.exportSymbols('PANDUIT-APPS-PoE-MIB', PYSNMP_MODULE_ID=panduitAppsPoE)

# Types
mibBuilder.exportSymbols('PANDUIT-APPS-PoE-MIB', PanduitPoEPlusOperMode=PanduitPoEPlusOperMode)

# Objects
mibBuilder.exportSymbols('PANDUIT-APPS-PoE-MIB', panduitAppsPoE=panduitAppsPoE, panduitAppsPoENotifications=panduitAppsPoENotifications, panduitPoEPoETable=panduitPoEPoETable, panduitPoEPoEEntry=panduitPoEPoEEntry, panduitPoEPoEIndex=panduitPoEPoEIndex, panduitPoEPoEForcePwr=panduitPoEPoEForcePwr, panduitPoEPoEDetectControl=panduitPoEPoEDetectControl, panduitPoEPoEMPSType=panduitPoEPoEMPSType, panduitPoELegacyDelay=panduitPoELegacyDelay, panduitPoEPlus=panduitPoEPlus, panduitPoEPlusScalarObjects=panduitPoEPlusScalarObjects, panduitPoEPlusHiPwrEnable=panduitPoEPlusHiPwrEnable, panduitPoePlusPDPowerMonEnable=panduitPoePlusPDPowerMonEnable, panduitPoePlusBackoffEnable=panduitPoePlusBackoffEnable, panduitPoEPlusTabularObjects=panduitPoEPlusTabularObjects, panduitPoePlusPortPowerTable=panduitPoePlusPortPowerTable, panduitPoePlusPortPowerEntry=panduitPoePlusPortPowerEntry, panduitPoePlusPortPwrIndex=panduitPoePlusPortPwrIndex, panduitPoePlusPortPwrMaxPower=panduitPoePlusPortPwrMaxPower, panduitPoePlusPortPwrActPower=panduitPoePlusPortPwrActPower, panduitAppsPoEConformance=panduitAppsPoEConformance, panduitAppsPoEGroups=panduitAppsPoEGroups, panduitAppsPoECompliances=panduitAppsPoECompliances)

# Notifications
mibBuilder.exportSymbols('PANDUIT-APPS-PoE-MIB', panduitPoEPortPowerStatusOff=panduitPoEPortPowerStatusOff, panduitPoEPortPDDetectionFault=panduitPoEPortPDDetectionFault, panduitPoEPortPowerStatusOn=panduitPoEPortPowerStatusOn, panduitPoEPortPowerStatusFault=panduitPoEPortPowerStatusFault)

# Groups
mibBuilder.exportSymbols('PANDUIT-APPS-PoE-MIB', panduitAppsPoEGeneralGroup=panduitAppsPoEGeneralGroup, panduitAppsPoEDeprecatedGroup=panduitAppsPoEDeprecatedGroup, panduitAppsPoENotificationGroup=panduitAppsPoENotificationGroup, panduitAppsPoEPoEPlusGroup=panduitAppsPoEPoEPlusGroup)
