"""
Copyright (C) 2010 2011 Cisco Systems

This program is free software; you can redistribute it and/or         
modify it under the terms of the GNU General Public License         
as published by the Free Software Foundation; either version 2         
of the License, or (at your option) any later version.         
    
This program is distributed in the hope that it will be useful,         
but WITHOUT ANY WARRANTY; without even the implied warranty of         
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
GNU General Public License for more details.         
    
You should have received a copy of the GNU General Public License         
along with this program; if not, write to:         
The Free Software Foundation, Inc.         
59 Temple Place - Suite 330         
Boston, MA  02111-1307, USA.         
    
As a special exception, if other files instantiate classes, templates  
or use macros or inline functions from this project, or you compile         
this file and link it with other works to produce a work based         
on this file, this file does not by itself cause the resulting         
work to be covered by the GNU General Public License. However         
the source code for this file must still be made available in         
accordance with section (3) of the GNU General Public License.         
    
This exception does not invalidate any other reasons why a work         
based on this file might be covered by the GNU General Public         
License.
"""


est = {
	'BACnetReliabilityStr' : {
                8 : "Process Error",
		7 : "Unreliable Other",
		6 : "No Output",
		5 : "Shorted Loop",
		4 : "Open Loop",
		3 : "Under Range",
		2 : "Over Range",
		1 : "No Sensor",
		0 : "No Fault Detected",
	},

	'BACnetBinaryPVStr' : {
		1 : "Active",
		0 : "Inactive",
	},

	'BACnetEngUnitsStr' : {
		119 : "Units Unknown",
		118 : "Kilojoules per Kilogram Dry Air",
		117 : "Kilocalories per Kilogram Dry Air",
		116 : "Cubic Meters per Hour",
		115 : "Cubic Meters per Minute",
		114 : "Millimeters of Water",
		113 : "Feet of Water Column",
                112 : "Currency8",
		111 : "Minutes per Degree Celsius",
		110 : "Minutes per Degree Fahrenheit",
		105 : "MBH: Thousands of BTUH",
		104 : "Revolutions per Minute",
		103 : "Radians",
		102 : "PSI per Degree Fahrenheit",
		101 : "Per Second",
		100 : "Per Minute",
		99 : "Percent per Second",
		98 : "Percent",
		97 : "Parts per Billion",
		96 : "Parts per Million",
		95 : " ",
		94 : "Degrees Fahrenheit per Minute",
		93 : "Degrees Fahrenheit per Hour",
		92 : "Degrees Celsius per Minute",
		91 : "Degrees Celsius per Hour",
		90 : "Degrees",
		89 : "Gallons per Minute",
		88 : "Liters per Minute",
		87 : "Liters per Second",
		86 : "Imperial Gallons per Minute",
		85 : "Cubic Meters per Second",
		84 : "Cubic Feet per Minute",
		83 : "Gallons",
		82 : "Liters",
		81 : "Imperial Gallons",
		80 : "Cubic Meters",
		79 : "Cubic Feet",
		78 : "Miles per Hour",
		77 : "Feet per Minute",
		76 : "Feet per Second",
		75 : "Kilometers per Hour",
		74 : "Meters per Second",
		73 : "Second",
		72 : "Minute",
		71 : "Hour",
		70 : "Day",
		69 : "Week",
		68 : "Month",
		67 : "Year",
		66 : "Degree Days Fahrenheit",
		65 : "Degree Days Celsius",
		64 : "Degrees Fahrenheit",
		63 : "Degrees Kelvin",
		62 : "Degrees Celsius",
		61 : "Inches of Mercury",
		60 : "Centimeters of Mercury",
		59 : "Millimeters of Mercury",
		58 : "Inches of Water",
		57 : "Centimeters Of Water",
		56 : "Pounds Force per Square Inch",
		55 : "Bar",
		54 : "Kilopascals",
		53 : "Pascals",
		52 : "Tons Refrigeration",
		51 : "Horsepower",
		50 : "Btu per Hour",
		49 : "Megawatts",
		48 : "Kilowatts",
		47 : "Watts",
		46 : "Pounds Mass per Hour",
		45 : "Pounds Mass per Minute",
		44 : "Kilograms Mass per Hour",
		43 : "Kilograms Mass per Minute",
		42 : "Kilograms Mass per Second",
		41 : "Tons",
		40 : "Pounds Mass",
		39 : "Kilograms",
		38 : "Foot Candles",
		37 : "LUX",
		36 : "Lumen",
		35 : "Watts per Square Meter",
		34 : "Watts per Square Foot",
		33 : "Feet",
		32 : "Inch",
		31 : "Meters",
		30 : "Millimeters",
		29 : "Percent Relative Humidity",
		28 : "Grams Water per Kilogram Dry Air",
		27 : "Hertz",
		26 : "Cycles per Minute",
		25 : "Cycles per Hour",
		24 : "BTU per Pound Dry Air",
		23 : "Joules per Kilogram Dry Air",
		22 : "Ton Hour",
		21 : "Therm",
		20 : "BTU",
		19 : "Kilowatt Hours",
		18 : "Watt Hours",
		17 : "Kilo Joules",
		16 : "Joules",
		15 : "Power Factor",
		14 : "Degrees Phase",
		13 : "Megavolt Amperes Reactive",
		12 : "Kilovolt Amperes Reactive",
		11 : "Volt Amperes Reactive",
		10 : "Megavolt Amperes",
		9 : "Kilovolt Amperes",
		8 : "Volt Amperes",
		7 : "Megavolts",
		6 : "Kilovolts",
		5 : "Volts",
		4 : "Ohms",
		3 : "Amperes",
		2 : "Milliamperes",
		1 : "Square Feet",
		0 : "Square Meters",
	},

	'BACnetEngUnitsShortStr' : {
		119 : "???????",
		118 : "kJ/kg",
		117 : "kcal/kg",
		116 : "m3/h",
		115 : "m3/min",
		114 : "mm W.C.",
		113 : "ft W.C.",
		112 : "cg/cm2",
		111 : "min/øC",
		110 : "min/øF",
		105 : "MBTUH",
		104 : "RPM",
		103 : "rad",
		102 : "PSI/F",
		101 : "per sec",
		100 : "per min",
		99 : "%/sec",
		98 : "%",
		97 : "ppb",
		96 : "ppm",
		95 : " ",
		94 : "øF/min",
		93 : "øF/hr",
		92 : "øC/min",
		91 : "øC/hr",
		90 : "deg",
		89 : "GPM",
		88 : "L/min",
		87 : "L/s",
		86 : "imp GPM",
		85 : "m3/s",
		84 : "CFM",
		83 : "gal",
		82 : "l",
		81 : "imp gal",
		80 : "m3",
		79 : "ft3",
		78 : "MPH",
		77 : "ft/min",
		76 : "ft/sec",
		75 : "km/hr",
		74 : "m/sec",
		73 : "sec",
		72 : "min",
		71 : "hr",
		70 : "day",
		69 : "wk",
		68 : "mon",
		67 : "yr",
		66 : "deg days F",
		65 : "deg days C",
		64 : "øF",
		63 : "øK",
		62 : "øC",
		61 : "in Hg",
		60 : "cm Hg",
		59 : "mm Hg",
		58 : "in W.C.",
		57 : "cm W.C.",
		56 : "PSI",
		55 : "bar",
		54 : "kPa",
		53 : "Pa",
		52 : "tons",
		51 : "hp",
		50 : "Btu/hr",
		49 : "MW",
		48 : "kW",
		47 : "W",
		46 : "lb mass/hr",
		45 : "lb mass/min",
		44 : "kg/hr",
		43 : "kg/min",
		42 : "kg/sec",
		41 : "tons",
		40 : "lbs",
		39 : "kg",
		38 : "ft Candles",
		37 : "LUX",
		36 : "lumen",
		35 : "W/m2",
		34 : "W/ft2",
		33 : "ft",
		32 : "in",
		31 : "m",
		30 : "mm",
		29 : "% RH",
		28 : "g H2O/kg",
		27 : "Hz",
		26 : "CPM",
		25 : "CPH",
		24 : "BTU/lb",
		23 : "J/kg",
		22 : "ton hr",
		21 : "therm",
		20 : "Btu",
		19 : "kWH",
		18 : "WH",
		17 : "kJ",
		16 : "J",
		15 : "power factor",
		14 : "deg phase",
		13 : "MV A reactive",
		12 : "kV A reactive",
		11 : "V A reactive",
		10 : "MVA",
		9 : "kVA",
		8 : "VA",
		7 : "MV",
		6 : "kV",
		5 : "V",
		4 : "ohms",
		3 : "A",
		2 : "mA",
		1 : "ft2",
		0 : "m2",
	},

	'BACnetEventStateStr' : {
		5 : "High Alarm",
		4 : "Low Alarm",
		3 : "High Warning",
		2 : "Low Warning",
		1 : "Alarm",
		0 : "Normal",
	},

	'BACnetEventTypeStr' : {
                8 : "Change Of Life Safety",
                7 : "Buffer Ready",
                6 : "Complex Event Type",
		5 : "Out Of Range",
		4 : "Floating Limit",
		3 : "Command Fail",
		2 : "Change Of Value",
		1 : "Change Of State",
                0 : "Change Of Bitstring",
	},

	'BACnetEventTransitionBitsStr' : {
		2 : "To Normal",
		1 : "To Fault",
		0 : "To Off Normal",
	},

	'BACnetPolarityStr' : {
		1 : "Reverse Polarity",
		0 : "Normal Polarity",
	},

	'BACnetDeviceStatusStr' : {
                5 : "Backup In Progress",
		4 : "Non-Operational",
		3 : "Download In Progress",
		2 : "Download Required",
		1 : "Operational Read Only",
		0 : "Operational",
	},

	'BACnetProgramStateStr' : {
		5 : "Unloading",
		4 : "Halted",
		3 : "Waiting",
		2 : "Running",
		1 : "Loading",
		0 : "Idle",
	},

	'BACnetObjectTypeStr' : {
                22 : "LifeSafetyZone",
                21 : "LifeSafetyPoint",
                20 : "Trend Log",
                19 : "MultiState Value",
                18 : "Averaging",
		17 : "Schedule",
		16 : "Program",
                15 : "Notification Class",
		14 : "MultiState Output",
		13 : "MultiState Input",
		12 : "Loop",
		11 : "Group",
		10 : "File",
		9 : "Event Enrollment",
		8 : "Device",
		7 : "Command",
		6 : "Calendar",
		5 : "Binary Value",
		4 : "Binary Output",
		3 : "Binary Input",
		2 : "Analog Value",
		1 : "Analog Output",
		0 : "Analog Input",
	},

	'BACnetPropertyIDStr' : {
                0: 'Acked Transistions',
                1: 'Ack Required',
                2: 'Action',
                3: 'Action Text',
                4: 'Active Text',
                5: 'Active VT Sessions', 
                8: 'All', 
                9: 'AllWritesSuccessful',
                10: 'APDU Segment Timeout',
                11: 'APDU Timeout',
                12: 'Application Software Revision',
                13: 'Archive',
                14: 'Bias',
                15: 'Power Factor',
                16: 'Change Of State Time',
                18: 'Confirmed Recipient List',
                19: 'Controlled Variable Reference',
                23: 'Date List',
                26: 'Derivative Constant',
                27: 'Derivative Constant Units',
                28: 'Description',
                29: 'DescriptionOfHalt',
                30: 'Device Address Binding',
                31: 'Device Type',
                32: 'Effective Period',
                33: 'Elapsed Active Time',
                36: 'State',
                37: 'Event Type',
                38: 'Exception Schedule',
                41: 'File Access Method',
                42: 'File Size',
                43: 'File Type',
                44: 'Firmware Revision',
                46: 'Inactive Text',
                47: 'In Process',
                48: 'Instance Of',
                49: 'Integral Constant',
                50: 'Integral Constant Units',
                53: 'List Of Group Members', 
                54: 'List Of ObjectPropertyReferences',
                56: 'Local Date',
                57: 'Local Time',
                58: 'Location',
                61: 'Maximum Output',
                62: 'Max Message Length Supported',
                65: 'Maximum Present Value',
                66: 'Minimum Off Time',
                67: 'Minimum On Time',
                68: 'Minimum Output',
                69: 'Minimum Present Value',
                70: 'Model Name',
                71: 'Modification Date',
                73: 'Number of APDU Retries',
                74: 'Number Of States',
                75: 'Object Identifier',
                76: 'Object List',
                77: 'Object Name',
                78: 'Object Property Reference',
                79: 'Object Type',
                80: 'Optional',
                81: 'Out Of Service',
                82: 'Output Units',
                83: 'Parameter List',
                84: 'Polarity',
                85: 'Present Value',
                87: 'Priority Array',
                88: 'Priority For Writing',
                90: 'Program Change',
                91: 'Program Location',
                92: 'Program State',
                93: 'Proportional Constant',
                94: 'Proportional Constant Units',
                95: 'Protocol Conformance Class',
                96: 'Protocol Object Types Supported',
                97: 'Protocol Services Supported',
                98: 'Protocol Version',
                99: 'Read Only',
                100: 'Reason For Halt',
                103: 'Reliability',
                104: 'Relinquish Default',
                105: 'Required',
                106: 'Resolution',
                107: 'Segmentation Supported',
                108: 'Setpoint',
                109: 'Setpoint Reference',
                110: 'State Text',
                111: 'Status Flags',
                112: 'Mode: System',
                114: 'Time of Active Time Reset',
                115: 'Time of State Count Reset',
                117: 'Units',
                118: 'Update Interval',
                120: 'BACnet Vendor ID',
                121: 'Vendor Name',
                122: 'VT Classes Supported',
                123: 'Weekly Schedule'
        },

        'BACnetPropertyTypeStr' : {
		122 : "Status Flags",
		121 : "VAV1 Flow Control",
		120 : "TOD Event Type",
		119 : "Channel Information",
		118 : "Heat Cool Mode",
		117 : "VAS Votes",
		116 : "Analog Type",
		115 : "PCM Operation Mode",
		114 : "Object Types Supported",
		113 : "Event Enable Select",
		112 : "PCM Display Packet",
		111 : "Analog Input Block",
		110 : "Event Class",
		109 : "Schedule Member",
		108 : "Special Event",
		107 : "Time Event Value",
		106 : "Area Member",
		105 : "Op Mode",
		103 : "Date Time Value",
		102 : "Object Reference",
		101 : "Property Reference",
		100 : "Object Const",
		95 : "Week N Day",
		94 : "VT Session",
		93 : "VT Class",
		92 : "Time Value",
		91 : "Time Stamp",
		90 : "Special Event",
		89 : "Services Supported",
		88 : "Segmentation",
		87 : "Property Value",
		86 : "Property States",
		85 : "Property Reference",
		84 : "Program State",
		83 : "Program Request",
		82 : "Program Error",
		81 : "Priority Value",
		79 : "Object Property Value",
		78 : "Notification Rule",
		77 : "Mail",
		76 : "File Access Method",
		75 : "Event Transition",
		74 : "Event Parameter",
		73 : "Calendar Entry",
		72 : "Address",
		71 : "Action Command",
		70 : "Action",
		64 : "Device Status",
		62 : "Object Property Reference",
		61 : "Date Range",
		60 : "Date Time",
		59 : "Polarity",
		58 : "Engineering Units",
		57 : "Binary Present Value",
		55 : "Event Type",
		54 : "Event State",
		53 : "Reliability",
		52 : "Property ID",
		51 : "Object Type",
		50 : "Object ID",
		137 : "Custom Field",
		12 : "Object Identifier",
		11 : "Time",
		10 : "Date",
		9 : "Enumerated",
		8 : "BitString",
		7 : "CharacterString",
		6 : "ByteString",
		5 : "Double",
		4 : "Real",
		3 : "SignedInt",
		2 : "UnsignedInt",
		1 : "Boolean",
		0 : "Null",
	}

}

