"""
Copyright (C) 2003 2010 2011 Cisco Systems

This program is free software; you can redistribute it and/or         
modify it under the terms of the GNU General Public License         
as published by the Free Software Foundation; either version 2         
of the License, or (at your option) any later version.         
    
This program is distributed in the hope that it will be useful,         
but WITHOUT ANY WARRANTY; without even the implied warranty of         
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         
GNU General Public License for more details.         
    
You should have received a copy of the GNU General Public License         
along with this program; if not, write to:         
The Free Software Foundation, Inc.         
59 Temple Place - Suite 330         
Boston, MA  02111-1307, USA.         
    
As a special exception, if other files instantiate classes, templates  
or use macros or inline functions from this project, or you compile         
this file and link it with other works to produce a work based         
on this file, this file does not by itself cause the resulting         
work to be covered by the GNU General Public License. However         
the source code for this file must still be made available in         
accordance with section (3) of the GNU General Public License.         
    
This exception does not invalidate any other reasons why a work         
based on this file might be covered by the GNU General Public         
License.
"""
from mpx_test import DefaultTestFixture, main

import time

from mpx.lib.node import CompositeNode
from mpx.lib.configure import REQUIRED, set_attribute, get_attribute
from mpx.lib.event import EventProducerMixin
from mpx.lib.node import as_internal_node, CompositeNode
from mpx.lib.threading import Lock
from mpx.lib import socket

from mpx.service.hal.alarms import NewAlarmsEvent
from mpx.service.hal.alarms import Alarm

from ewebconnect import EWebConnectAlarmClient

class TestCase(DefaultTestFixture, CompositeNode, EventProducerMixin):
    def __init__(self, *args, **kw):
        DefaultTestFixture.__init__(self, *args,**kw)
        EventProducerMixin.__init__(self)
        CompositeNode.__init__(self)
        return
    def setUp(self):
        DefaultTestFixture.setUp(self)
        server_socket = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
        server_socket.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1)
        server_socket.bind(('localhost',0)) # Bind to any available port on
                                            # localhost.
        server_socket.listen(5)
        sockname = server_socket.getsockname()
        ##
        # Socket ready to accept "eWebConnect" Alarm messages.
        self.server_socket = server_socket
        ##
        # The "eWebConnect" host.
        self.sever_address = sockname[0]
        ##
        # The "eWebConnect" post.
        self.server_port = sockname[1]
        self.new_node_tree()
        root = as_internal_node('/')
        self.configure({'name':'Test Case', 'parent':'/'})
        client = EWebConnectAlarmClient()
        client.configure({'name':'eWebConnect', 'parent':self,
                          'host':'localhost',
                          'port':self.server_port})
        as_internal_node('/').start()
        return
    def tearDown(self):
        self.del_node_tree()
        DefaultTestFixture.tearDown(self)
        return
    def test_alarm_1(self):
        a = Alarm(id=1, type='Non-Critical', source='1',
                  data='Alarm generated by test_alarm_1',
                  state=68,  timestamp=time.time())
        e = NewAlarmsEvent(self, [a,])
        self.event_generate(e)
        alarm_text = self.accept_one_alarm(10)
        # Assert that "N/A" is not in the alarm text.
        if alarm_text.find('N/A') != -1:
            self.fail(
                "Alarm Message %r contains failed conversion text (%r)." %
                (alarm_text, "N/A"))
        return
    def accept_one_alarm(self, timeout):
        skt,add = self.server_socket.accept(timeout)
        result = ''
        next = skt.recv(128,timeout)
        while next:
            result += next
            next = skt.recv(128,timeout)
        return result

if __name__ == '__main__':
    main()
